version: "3.8"
services:
  meilisearch:
    container_name: kiwi-meilisearch
    image: getmeili/meilisearch
    restart: always
    environment:
      MEILI_MASTER_KEY: "gCVyJtPaH7CvxB5HDUz1yDenTeahrmg9ynVrFFJ0hKI"
    ports:
      - "7700:7700"
  kiwi-db:
    container_name: kiwi-db
    restart: always
    image: postgres:15.4-alpine3.18
    ports:
      - "5443:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: kiwi
    volumes:
      - ../static/cities5000.txt:/home/cities5000.txt