version: "3.8"
services:
  kiwi-meilisearch:
    container_name: kiwi-meilisearch
    image: getmeili/meilisearch
    restart: always
    environment:
      MEILI_MASTER_KEY: "${MEILISEARCH_API_KEY}"
    ports:
      - "7700:7700"
    networks:
      - kiwi-network
  kiwi-db:
    container_name: kiwi-db
    restart: always
    image: postgres:15.4-alpine3.18
    ports:
      - "5443:5432"
    environment:
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_DB: "${POSTGRES_DB}"
    volumes:
      - ../static/cities5000.txt:/home/cities5000.txt
    networks:
      - kiwi-network
  
  kiwi-app:
    image: kiwi:latest
    container_name: kiwi-app
    build:
      context: .
      dockerfile: ../Dockerfile
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - kiwi-db
      - kiwi-meilisearch
    networks:
      - kiwi-network
networks:
  kiwi-network:
    driver: bridge
