version: "3.8"
services:
  kiwi-db:
    container_name: kiwi-db
    restart: always
    image: postgres:15.4-alpine3.18
    ports:
      - "5443:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: kiwi
