//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"time"
)

type Cities struct {
	ID               int32 `sql:"primary_key"`
	Name             *string
	Asciiname        *string
	Alternatenames   *string
	Latitude         *float64
	Longitude        *float64
	FeatureClass     *string
	FeatureCode      *string
	CountryCode      *string
	Cc2              *string
	Admin1Code       *string
	Admin2Code       *string
	Admin3Code       *string
	Admin4Code       *string
	Population       *int32
	Elevation        *int32
	Dem              *int32
	Timezone         *string
	ModificationDate *time.Time
}
