//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

type Profiles struct {
	ID        int32 `sql:"primary_key"`
	UserID    int64
	UserTgID  int64
	Name      *string
	Age       *int32
	Gender    *string
	PhotoID   *string
	About     *string
	IsActive  bool
	Latitude  *float64
	Longitude *float64
}
