//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import "errors"

type Session string

const (
	Session_FillProfile   Session = "fill_profile"
	Session_FillBlacklist Session = "fill_blacklist"
	Session_None          Session = "none"
)

func (e *Session) Scan(value interface{}) error {
	var enumValue string
	switch val := value.(type) {
	case string:
		enumValue = val
	case []byte:
		enumValue = string(val)
	default:
		return errors.New("jet: Invalid scan value for AllTypesEnum enum. Enum value has to be of type string or []byte")
	}

	switch enumValue {
	case "fill_profile":
		*e = Session_FillProfile
	case "fill_blacklist":
		*e = Session_FillBlacklist
	case "none":
		*e = Session_None
	default:
		return errors.New("jet: Invalid scan value '" + enumValue + "' for Session enum")
	}

	return nil
}

func (e Session) String() string {
	return string(e)
}
