//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

type Users struct {
	ID           int32 `sql:"primary_key"`
	TelegramID   int64
	FirstName    *string
	LastName     *string
	Username     string
	LanguageCode *string
	IsPremium    bool
	PhotoURL     *string
	Session      Session
}
