name: Deploy KIWI

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - stage-dev
  push:
    branches:
      - stage-dev

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Default branch
        run: |
          git config --global init.defaultBranch main

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check Go is installed
        id: check-go
        run: |
          if command -v go &> /dev/null; then
            echo "go_installed=true" >> $GITHUB_ENV
          else
            echo "go_installed=false" >> $GITHUB_ENV
          fi

      - name: Setup go
        if: steps.check-go.outputs.go_installed == 'false'
        uses: actions/setup-go@v5
        with:
          go-version: '1.x'

      - name: Build bot
        run: |
          go build -o start-bot ./cmd/bot/main.go
      
      - name: Build meilisearch
        run: |
          go build -o start-meilisearch ./cmd/meilisearch/main.go
      
      - name: Build location
        run: |
          go build -o start-location ./cmd/location/main.go

  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: ${{ needs.build.result == 'success' }}
    steps:
      - name: Deploy to remote server via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
              cd kiwi
              
              if pgrep -f "start-bot" > /dev/null; then
                echo "Stopping the existing application..."
                pkill -f "start-bot" || echo "Failed to stop the application, continuing with deployment."
              else
                echo "No running application found."
              fi

              git pull origin stage-dev || { echo "Git pull failed"; exit 1; }

              echo "Building the new version..."
              go build -o start-bot ./cmd/bot/main.go || { echo "Build failed"; exit 1; }

              echo "Starting the new version..."
              nohup ./start-bot > app.log 2>&1 & echo $! > start-bot.pid || { echo "Failed to start the application"; exit 1; }

              echo "Deploy complete!"