name: Check KIWI build

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main



      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Default branch
        run: |
          git config --global init.defaultBranch main

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check if Go is installed
        id: check-go
        run: |
          if command -v go &> /dev/null; then
            echo "Go is already installed."
            echo "go_installed=true" >> $GITHUB_ENV
          else
            echo "Go is not installed."
            echo "go_installed=false" >> $GITHUB_ENV

      - name: Install Go if not installed
        if: steps.check-go.outputs.go_installed == 'false'
        uses: actions/setup-go@v5
        with:
          go-version: '1.x'

      - name: Debug build
        run: |
          go build -o start-bot ./cmd/bot/main.go
    
